@startuml

title "Post AuthN Organization Selection"
scale 1.09
autonumber
participant acp_ui as "ACP UI\nCloudentity"
participant acp_api as "ACP API\nCloudentity"
participant post_authn_ui as "Post AuthN UI\nCustomer"
participant post_authn_api as "Post AuthN API\nCustomer"
participant customer_api as "Organizations API\nCustomer"

acp_ui <-->> acp_api: Authenticate User

acp_ui <- acp_api: Post-AuthN Redirect
post_authn_ui <- acp_ui: Redirect Post-AuthN
post_authn_ui -> post_authn_api: Request User and Organizations

acp_api <- post_authn_api: Request AuthN System
acp_api -> post_authn_api: Return System Access Token

acp_api <- post_authn_api: Request Session login_id, login_state
acp_api -> post_authn_api: Return User Session

post_authn_api -> customer_api: Request User Organizations

group If user found
  post_authn_api <- customer_api: Return User Organizations
  post_authn_ui <- post_authn_api: Return UserId and Organizations
  group If multiple organizations
    post_authn_ui -> post_authn_ui: Build Organization Selection
    post_authn_ui -> post_authn_ui: User selects organization
    post_authn_ui -> post_authn_ui: User clicks submit
    post_authn_ui -> post_authn_api: Complete AuthN\nwith OrganizationId
  end
  group If single Organization
    post_authn_ui -> post_authn_ui: Auto select the 1 organization
    post_authn_ui -> post_authn_ui: Auto Execute submit
    post_authn_ui -> post_authn_api: Complete AuthN\nwith OrganizationId
  end
  group verify submitted organization
    post_authn_api -> customer_api: Request User Organizations
    post_authn_api <- customer_api: Return User Organizations
    post_authn_api -> post_authn_api: Verify Submitted OrganizationId\nis in User Record
  end
  acp_api <- post_authn_api: Complete AuthN
  acp_api -> post_authn_api: Return complete redirect_to
  post_authn_ui <- post_authn_api: Return redirect_to
  post_authn_ui-> post_authn_ui: Execute redirect_to
  acp_ui <- post_authn_ui: Redirect to ACP
end

group If user not found
  post_authn_api <- customer_api: Return User Not Found
  acp_api <- post_authn_api: Abort AuthN
  acp_api -> post_authn_api: Return abort redirect_to
  post_authn_ui <- post_authn_api: Return User Not Found
  post_authn_ui -> post_authn_ui: Display User Error
end

group If error
  post_authn_ui -> post_authn_ui: System Failure detected
  post_authn_ui -> post_authn_ui: Display System Error
end

@enduml
